services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
      - node_modules:/workspace/node_modules
    command: sleep infinity
    environment:
      NODE_ENV: development
    ports:
      - "5173:5173"
      - "3000:3000"
      - "8000:8000"

volumes:
  node_modules:
